"""Generate one self-contained prompt from the canonical skill; no dependencies."""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / 'skills' / 'spring-boot-reviewer-lite'
OUTPUT = ROOT / 'portable' / 'spring-boot-reviewer-lite.md'
REFERENCES = (
    ('review-checklist.md', 'review-checklist'),
    ('report-format.md', 'report-format'),
)


def render():
    core = (SKILL / 'SKILL.md').read_text(encoding='utf-8').split('---', 2)[2].strip()
    for filename, anchor in REFERENCES:
        core = core.replace(f'(references/{filename})', f'(#{anchor})')
    sections = [
        '<!-- Generated by tools/build_portable.py; edit the canonical skill instead. -->',
        '# Spring Boot Reviewer Lite — portable instructions',
        'Use these instructions with the source files supplied by the user. '
        'If you have authorized project-file access, inspect the requested scope. '
        'Otherwise ask for the relevant source snippets and configuration; never claim '
        'to have accessed files or executed tests you cannot access. Follow the host '
        'assistant\'s tool permissions. If the supplied scope is incomplete, state the limits. '
        'The complete checklist and report format are included below; no skill loader is required.',
        core,
    ]
    for filename, anchor in REFERENCES:
        body = (SKILL / 'references' / filename).read_text(encoding='utf-8').strip()
        # Stable headings for the rewritten links, followed by the unmodified reference.
        sections.extend([f'## {anchor}', body])
    return '\n\n'.join(sections) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if the committed bundle is stale')
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding='utf-8') != expected:
            parser.exit(1, 'Portable bundle is stale. Run python tools/build_portable.py\n')
        print('PASS: portable bundle matches canonical skill and references')
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected, encoding='utf-8', newline='\n')
        print(f'Generated {OUTPUT}')


if __name__ == '__main__':
    main()
